# Ejercicio de manipulación de datos

Para realizar este ejercicio vamos a descargamos los ficheros correspondientes al curso 2024-25 (UCM-Acceso-2024-25-Anonimizado.csv) de la web
https://www.universidata.es/datasets/ucm-acceso.
Lo dejamos en nuestra carpeta llamada `Data` y lo importamos como un data frame llamado `df`.



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


/var/folders/gz/w9zmh03s61l021wmll3psm_c0000gn/T/ipykernel_5730/663826302.py:3: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv = pd.read_csv("./Data/ucm-acceso-2024-25-anonimizado.csv")


Al hacer la carga de los datos desde el fichero hasta el data frame, me ha salido una advertencia (***DtypeWarning***) de Pandas: una de las columnas del csv contiene datos de tipos diferentes (***Columns (35) have mixed types.***). Esto conviene explorarlo, empezamos mirando las dimensiones, es decir, el número de filas y columnas.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


(14019, 78)


## Explorar filas y columnas

Una tabla puede tener un gran número de entradas o filas, es por ello que se recomienda explorar una parte del dataframe con `head` y `tail`.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
0,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
1,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
2,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
3,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
4,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
14014,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,2.0,Sin Estudios,12.0,Amos de casa,5.0,Estudios Superiores,NaN,NaN
14015,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,11.0,Jubilado
14016,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,5.0,Estudios Superiores,11.0,Jubilado,2.0,Sin Estudios,3.0,Técnicos y profesionales de apoyo
14017,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."
14018,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


Index(['IMPORTANTE', 'cod_universidad', 'des_universidad', 'curso_academico',
       'cod_campus', 'des_campus', 'cod_centro', 'des_centro',
       'cod_naturaleza_centro', 'des_naturaleza_centro', 'cod_tipo_estudio',
       'des_tipo_estudio', 'cod_titulacion', 'des_titulacion',
       'cod_comunidad_centro_sec', 'des_comunidad_centro_sec',
       'cod_provincia_centro_sec', 'des_provincia_centro_sec',
       'cod_municipio_centro_sec', 'des_municipio_centro_sec',
       'lat_municipio_centro_sec', 'lon_municipio_centro_sec',
       'cod_naturaleza_centro_sec', 'des_naturaleza_centro_sec',
       'nota_admision', 'cod_pais_fin_estudio_acceso',
       'des_pais_fin_estudio_acceso', 'lat_pais_fin_estudio_acceso',
       'lon_pais_fin_estudio_acceso', 'cod_continente_fin_estudio_acceso',
       'des_continente_fin_estudio_acceso',
       'cod_agregacion_paises_fin_estudio_acceso',
       'des_agregacion_paises_fin_estudio_acceso', 'cod_estudio_acceso',
       'des_estudio_acceso', 'cod_e

Puede interesarnos una o varias columnas. Podemos seleccionar el número de columnas que queramos mediante los corchetes.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,des_titulacion,des_comunidad_centro_sec,nota_admision
0,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,"7,586"
1,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Galicia,"12,082"
2,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Murcia,"6,317"
3,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,"11,728"
4,GRADO EN DERECHO (2020) INSTITUTO SUPERIOR DE ...,Madrid,NaN
...,...,...,...
14014,GRADO EN CIENCIAS DE LAS RELIGIONES,Andalucía,"5,65"
14015,GRADO EN CIENCIAS DE LAS RELIGIONES,NaN,"7,63"
14016,GRADO EN CIENCIAS DE LAS RELIGIONES,NaN,5
14017,GRADO EN CIENCIAS DE LAS RELIGIONES,Madrid,"13,353"


***Pero recuerdo que me interesa explorar la columna 35.***


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


'cod_especialidad_acceso'


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,cod_especialidad_acceso
0,NaN
1,0703
2,NaN
3,NaN
4,NaN
...,...
14014,NaN
14015,NaN
14016,0204
14017,NaN


### Problema: Los códigos como 0703 no deberían tratarse como números.

***Si Pandas intenta interpretar el código 0703 como un número, 0703 se convierte en 703, perdiendo el 0 inicial.***


### Solución 1

Decir a Pandas que lea el archivo de otra manera para determinar los tipos de las columnas (`low_memory = False`).




<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,cod_especialidad_acceso
0,NaN
1,0703
2,NaN
3,NaN
4,NaN
...,...
14014,NaN
14015,NaN
14016,0204
14017,NaN


### Solución 2:

Especificar explícitamente el tipo de la columna que puede generar el conflicto (`dtype={"cod_especialidad_acceso": "str"}`) es la solución más adecuada, ya que nos permite controlar cómo interpreta Pandas los datos al leer el archivo.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,cod_especialidad_acceso
0,NaN
1,0703
2,NaN
3,NaN
4,NaN
...,...
14014,NaN
14015,NaN
14016,0204
14017,NaN


## Seleccionar unas filas concretas


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
0,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,2,Familia numerosa general,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...
1,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,4.0,Estudios Secundarios,2.0,Técnicos y profesionales científicos e intelec...


## Filtrar

Se **filtran** las filas u observaciones que cumplen una determinada restricción.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
34,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28053915.0,Instituto Superior de Derecho y Economía,2,Privado,...,1,No,3.0,Estudios Primarios,1.0,Directores y gerentes,3.0,Estudios Primarios,1.0,Directores y gerentes
858,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,..."
862,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,1,No,5.0,Estudios Superiores,14.0,"Otra situación (Rentistas,…)",4.0,Estudios Secundarios,NaN,NaN
910,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,NaN,NaN,NaN,NaN
963,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,7.0,Artesanos y trabajadores cualificados de las i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13642,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28043119.0,Facultad de Educación,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
13758,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027837.0,Facultad de Ciencias Químicas,1,Público,...,1,No,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,4.0,Estudios Secundarios,8.0,Operadores de instalaciones y maquinaria y mon...
13781,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,2,Familia numerosa general,4.0,Estudios Secundarios,4.0,Empleados de tipo contable y administrativo,4.0,Estudios Secundarios,11.0,Jubilado
13846,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
910,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,4.0,Estudios Secundarios,NaN,NaN,NaN,NaN,NaN,NaN
963,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,7.0,Artesanos y trabajadores cualificados de las i...
1008,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,4.0,Estudios Secundarios,1.0,Directores y gerentes
1038,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,11.0,Jubilado
10305,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,3.0,Estudios Primarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,3.0,Técnicos y profesionales de apoyo
10919,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,1.0,Directores y gerentes
13846,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027001.0,Facultad de Derecho,1,Público,...,1,No,5.0,Estudios Superiores,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...


## Ordenar

Se pueden **ordenar** los datos por determinadas columnas.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
14016,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,5.0,Estudios Superiores,11.0,Jubilado,2.0,Sin Estudios,3.0,Técnicos y profesionales de apoyo
4680,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027710.0,Facultad de Filología,1,Público,...,1,No,5.0,Estudios Superiores,NaN,NaN,NaN,NaN,NaN,NaN
5179,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027035.0,Facultad de Medicina,1,Público,...,2,Familia numerosa general,3.0,Estudios Primarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
1555,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027746.0,Facultad de Geografía e Historia,1,Público,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,4.0,Estudios Secundarios,4.0,Empleados de tipo contable y administrativo
7752,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027710.0,Facultad de Filología,1,Público,...,1,No,4.0,Estudios Secundarios,12.0,Amos de casa,3.0,Estudios Primarios,7.0,Artesanos y trabajadores cualificados de las i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14013,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14014,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,2.0,Sin Estudios,12.0,Amos de casa,5.0,Estudios Superiores,NaN,NaN
14015,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",5.0,Estudios Superiores,11.0,Jubilado
14017,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,28027761.0,Facultad de Filosofía,1,Público,...,1,No,4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,...",4.0,Estudios Secundarios,5.0,"Trabajadores de los servicios de restauración,..."



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,IMPORTANTE,cod_universidad,des_universidad,curso_academico,cod_campus,des_campus,cod_centro,des_centro,cod_naturaleza_centro,des_naturaleza_centro,...,cod_familia_numerosa,des_familia_numerosa,cod_nivel_estudios_madre,des_nivel_estudios_madre,cod_ocupacion_madre,des_ocupacion_madre,cod_nivel_estudios_padre,des_nivel_estudios_padre,cod_ocupacion_padre,des_ocupacion_padre
752,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
795,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,13.0,Incapacitados para trabajar,4.0,Estudios Secundarios,1.0,Directores y gerentes
751,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,10.0,Parado,5.0,Estudios Superiores,1.0,Directores y gerentes
753,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,3,Familia numerosa especial,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
754,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1012,"Campus del centro ""Centro de Enseñanza Superio...",28051219.0,Instituto de Estudios Bursátiles,2,Privado,...,1,No,5.0,Estudios Superiores,12.0,Amos de casa,5.0,Estudios Superiores,4.0,Empleados de tipo contable y administrativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14009,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,1,No,5.0,Estudios Superiores,3.0,Técnicos y profesionales de apoyo,4.0,Estudios Secundarios,1.0,Directores y gerentes
14010,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,1.0,Directores y gerentes,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14011,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,2,Familia numerosa general,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...
14012,LOS DATOS DE ESTA FILA NO CORRESPONDEN A UN SÓ...,10,Universidad Complutense de Madrid,2024-25,1001,Ciudad Universitaria,NaN,NaN,1,Público,...,1,No,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...,5.0,Estudios Superiores,2.0,Técnicos y profesionales científicos e intelec...


## Crear nuevas columnas

Podemos crear nuevas columnas resultado de realizar cálculos. 


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,Nombre,Edad,Ciudad,Menor_edad
0,Sonia,24,Madrid,True
1,Carmen,31,Sevilla,True
2,Marta,28,Valencia,True
3,Jose,40,Segovia,True
4,Nieves,16,Madrid,False
5,Carlitos,12,Madrid,False


## Eliminar columnas


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,Nombre,Edad,Ciudad
0,Sonia,24,Madrid
1,Carmen,31,Sevilla
2,Marta,28,Valencia
3,Jose,40,Segovia
4,Nieves,16,Madrid
5,Carlitos,12,Madrid


## Renombrar columnas


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,Nombre,Edad,Población
0,Sonia,24,Madrid
1,Carmen,31,Sevilla
2,Marta,28,Valencia
3,Jose,40,Segovia
4,Nieves,16,Madrid
5,Carlitos,12,Madrid


## Añadir una fila con un valor nulo

Para añadir una fila, decimos que pasada la última fila (len(df)) se edita df.loc[ ] y se le asigna una lista de datos. En este caso, voy a aprovechar que añado una fila para dejar una celda sin dato. Por ejemplo, dejamos la edad sin conocer.

Aviso: cada vez que ejecutes esta intrucción, se añade una fila nueva.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


## Valores nulos


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,Nombre,Edad,Población
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False
4,False,False,False
5,False,False,False
6,False,True,False


## Eliminar filas con datos vacíos:

En ocasiones, no nos interesan las filas que no son completas. En estos casos se eliminan dichas filas.


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


,Nombre,Edad,Población
0,Sonia,24,Madrid
1,Carmen,31,Sevilla
2,Marta,28,Valencia
3,Jose,40,Segovia
4,Nieves,16,Madrid
5,Carlitos,12,Madrid


## Operaciones sobre una columna numérica

A continuación ponemos una muestra, para más detalle se puede consultar la documentación de Python (https://docs.python.org/es/3.14/builtins/functions.html).


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


25.166666666666668


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


40


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


12


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>


151

## Guardar datos


<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>



<div style="
    text-align: center;
    font-size: 10px;
">

ESCRIBE TU CÓDIGO PYTHON
</div>
